=== ingoha/pwdt-ss10/trunk/documents/cloverleaf/Cloverleaf-Schulung/training/Cloverleaf Aufbauschulung/JKA_lab/dietOrder.dtd
<!ELEMENT dietOrder (envelope? , dietician? , patient* )>
<!ELEMENT envelope (sent? , reference)>
<!ELEMENT dietician (id , nm , tel? , addr? )>
<!ELEMENT patient (id , nm , tel? , dob? , diet , clinicalObs? )>
<!ELEMENT diet (dietElement , dietInstruction? )>
<!ELEMENT dietInstruction (tray* , text* )>
<!ELEMENT clinicalObs (allergy? , bloodType? , weight? )>

<!ELEMENT allergy (code* )>
<!ELEMENT bloodType (code )>
<!ELEMENT dietElement (code* )>
<!ELEMENT dob (ts )>
<!ELEMENT id (code+ )>
<!ELEMENT reference (code+ )>
<!ELEMENT sent (ts )>
<!ELEMENT tel (url* )>
<!ELEMENT weight (code )>

<!ELEMENT addr (STR , HNR? , ZIP , CTY)>
<!ATTLIST addr		USE	CDATA	#IMPLIED >
<!ELEMENT STR (#PCDATA )>
<!ELEMENT ZIP (#PCDATA )>
<!ELEMENT HNR (#PCDATA )>
<!ELEMENT CTY (#PCDATA )>
<!ELEMENT code (#PCDATA )>
<!ATTLIST code		type	CDATA	#IMPLIED
			unit	CDATA	#IMPLIED >
<!ELEMENT nm (GIV+, PFX* , FAM+ , SFX?)>
<!ELEMENT PFX (#PCDATA )>
<!ATTLIST PFX		Q	CDATA	#IMPLIED >
<!ELEMENT GIV (#PCDATA )>
<!ATTLIST GIV		Q	CDATA	#IMPLIED >
<!ELEMENT FAM (#PCDATA )>
<!ATTLIST FAM		Q	CDATA	#IMPLIED >
<!ELEMENT SFX (#PCDATA )>
<!ATTLIST SFX		Q	CDATA	#IMPLIED >
<!ELEMENT text (#PCDATA )>
<!ELEMENT tray (#PCDATA )>
<!ELEMENT ts (#PCDATA )>
<!ELEMENT url (#PCDATA )>
<!ATTLIST url		use	CDATA	#IMPLIED >

=== ingoha/pwdt-ss10/documents/cloverleaf/Cloverleaf-Schulung/training/Cloverleaf Aufbauschulung/JKA_lab/dietOrder544.xml
<?xml version="1.0" encoding="ISO-8859-1"?> 
<!DOCTYPE dietOrder SYSTEM "dietOrder.dtd">
<dietOrder>
<envelope>
  <sent><ts>200110261400</ts></sent>
  <reference><code>544</code></reference>      
</envelope>

<dietician>
  <id>
    <code type="N">0100</code>
  </id> 
  <nm>
    <GIV>Regina</GIV>
    <GIV>Johanna</GIV>
    <GIV>Maria</GIV>
    <PFX Q="NB">Graefin </PFX>
    <PFX Q="VV">von </PFX>
    <FAM Q="BR">Hochheim</FAM>
    <FAM Q="SP">Weilenfels</FAM>
    <SFX Q="PR">NCFSA</SFX>
  </nm>
  <tel>
    <url use="WP">tel:+49(30)8101-724</url>
    <url use="WP">fax:+49(30)8101-722</url>
    <url use="WP">e-mail:regina@diets.de</url>
  </tel>
  <addr USE="WP">
    <STR>Windsteiner Weg</STR>
    <HNR>45a</HNR>
    <ZIP>14165</ZIP>
    <CTY>Berlin</CTY>
  </addr>
</dietician>

<patient>
  <id>
    <code type="L">000073533</code>
  </id>
  <nm>
    <GIV>Gerard</GIV>
    <GIV>Christiaan</GIV>
    <PFX Q="VV">van </PFX>
    <FAM Q="BR">Geesteren</FAM>
    <SFX Q="PR">RI</SFX>
  </nm>
  <tel>
    <url use="H">tel:+31(10)2881600</url>
  </tel>
  <dob><ts>19600115</ts></dob>
  <diet>
    <dietElement>
      <code type="L">942</code>
      <code type="S">74398</code>
      <code type="S">99443</code> 
    </dietElement>
    <dietInstruction>
      <tray>early morning tray</tray>
    </dietInstruction>
  </diet>

  <clinicalObs>
    <bloodType><code>A NEG</code></bloodType>
    <weight><code unit="Kg">87</code></weight>   
  </clinicalObs> 
</patient>

</dietOrder>
